### ISSUE TITLE
How can i import this project into android studio?

### ISSUE THREAD

**Issue by ananth10** [coresystemsFSM/web-twilio-sparky#5]
It seems it is not android studio project. how i can import this into studio?

**Comment by FranziscaZarrai** [comment]
@ananth10 Hey there, indeed it is not an android studio project, it is a server :) so you can import it (maven) into IntellJ Idea for instance (not android studio - the regular intelliJ IDE) - you don't have to use IntellJ though, but it works quite well with it. Plus: Some of the classes are written in Kotlin (panguage by Jetbrains - publishers of IntelliJ IDE). 

The android project that goes with this server is here: https://github.com/coresystemsFSM/android-twilio-video-with-service
